export enum EVideoState {
  DRAFT = 'DRAFT',
  PUBLIC = 'PUBLIC',
  UNLISTED = 'UNLISTED',
  PRIVATE = 'PRIVATE',
  DELETED = 'DELETED',
  BLOCKED = 'BLOCKED',
  UPLOADER_DELETED = 'UPLOADER_DELETED',
}
