version: '3.9'
services:
# Nestjs backend
  isee-backend:
    container_name: isee-backend
    command: npm run start:dev
    env_file:
      - ./.env
    build:
      context: "./backend-server"
      dockerfile: "./dockerfile"
    volumes:
      - ./backend-server/src:/usr/src/app/src
      - static:/usr/src/static
    depends_on:
      - isee-mongodb
# Mongo database for the backend
  isee-mongodb:
    container_name: isee-mongodb
    image: "mongo:6.0.3"
    ports:
      - ${MONGO_PORT_EXT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - db:/data/db
    healthcheck:
      test: test $$(echo "db.runCommand("ping").ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
# Nginx reverse proxy
  isee-nginx:
    container_name: isee-nginx
    environment:
      BACKEND_PROXY_PASS: isee-backend:3000
    build: 
      context: "./nginx"
    ports:
    - "${NGINX_PORT}:80"
    volumes:
      - static:/usr/src/static:ro
    depends_on:
      - isee-backend
volumes:
  db:
  static: