version: '3.9'
services:
# Backend for the main API
  backend:
    env_file:
      - ./.env
    build:
      context: "./backend-server"
      dockerfile: "./DOCKERFILE.dev"
    volumes:
      - ./backend-server/src:/usr/src/app/src
    depends_on:
      - backend-mongodb
# Mongo database for the backend
  backend-mongodb:
    image: "mongo:6.0.3"
    ports:
      - ${MONGO_PORT_EXT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data/backend:/data/db
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
  nginx:
    image: "nginx:mainline-alpine"
    ports:
    - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend