version: '3.9'
services:
# Backend for the main API
  backend:
    build:
      context: "."
    ports:
      - ${BACKEND_PORT_EXT}:${BACKEND_PORT}
    volumes:
      - ./backend-server:/usr/src/app
    depends_on:
      - backend-mongodb
# Mongo database for the backend
  backend-mongodb:
    image: "mongo:6.0.3"
    ports:
      - ${MONGO_PORT_EXT}:27017
    environment:
      - TZ=Etc/UTC
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data/backend:/data/db
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s