version: '3.9'
services:
# Backend for the main API
  isee-backend:
    container_name: isee-backend
    env_file:
      - ./.env
    build:
      context: "./backend-server"
      dockerfile: "./dockerfile"
    volumes:
      - ./backend-server/src:/usr/src/app/src
      
    depends_on:
      - isee-mongodb
# Mongo database for the backend
  isee-mongodb:
    container_name: isee-mongodb
    image: "mongo:6.0.3"
    ports:
      - ${MONGO_PORT_EXT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data/backend:/data/db
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
  isee-nginx:
    container_name: isee-nginx
    build: 
      context: "./nginx"
    ports:
    - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./videofiles:/opt/static/videos
      - ./thumbfiles:/opt/static/thumbnails
      - ./nginx/nginx-local-node-server/logs:/logs
    depends_on:
      - isee-backend