export enum EVideoState {
  DRAFT = 'DRAFT',
  PUBLIC = 'PUBLIC',
  UNLISTED = 'UNLISTED',
  PRIVATE = 'PRIVATE',
  DELETED = 'DELETED',
  BLOCKED = 'BLOCKED',
  UPLOADER_DELETED = 'UPLOADER_DELETED',
}

export enum EVideoProcessing {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
  FAILED = 'FAILED',
}
