apiVersion: v1 
kind: Service 
metadata:
  name: isee-backend-external 
  labels:
    app: isee-backend
   
spec:
  selector:
    app: isee-backend
    
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 3000
      nodePort: 31002
