apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: isee-nginx 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: isee-nginx 
  template: 
    metadata: 
      labels: 
        app: isee-nginx 
    spec: 
      containers: 
      - name: isee-nginx 
        image: kamul/isee-nginx:v1 
        
        ports: 
        - containerPort: 4500 
     
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: isee-nginx-service 
spec: 
  selector: 
    app: isee-backend 
  type: LoadBalancer 
  ports: 
  - name: http-server
  - protocol: TCP 
    port: 4500
    targetPort: 4500
    nodePort: 30000