apiVersion: v1 
kind: Service 
metadata:
  name: mongodb-head-service
  
   
spec:
  selector:
    app: isee-mongodb
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017 
      targetPort: 27017

