apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: isee-backend 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: isee-backend 
  template: 
    metadata: 
      labels: 
        app: isee-backend 
    spec: 
      containers: 
      - name: isee-backend 
        image: backend-isee-backend:latest
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 3000 
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key:  mongo-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: mongo-password
        - name: BACKEND_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: backend-jwt-secret
        - name: BACKEND_MAILER_EMAIL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: backend-mailer-email
        - name: BACKEND_MAILER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: backend-mailer-password
        envFrom:
          - configMapRef:
              name: backend-config
        volumeMounts:
        - name: my-volume
          mountPath: /usr/src/static
      volumes:
      - name: my-volume
        hostPath:
          path: /media/chfr/SSD980/Supinfo_2022_2023/3PROJ/iSee-3PROJ/Kubernetes/static
     
     
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: isee-backend-service 
spec: 
  selector: 
    app: isee-backend 
  ports: 
  - protocol: TCP
    port: 3000 
    targetPort: 3000 
  type: ClusterIP 