apiVersion: v1 
kind: Service 
metadata:
  name: isee-mongodb-service
  labels:
    app: isee-mongodb
    app.kubernetes.io/name: isee-mongodb-0
spec:
  selector:
    app: isee-mongodb
    statefulset.kubernetes.io/pod-name: isee-mongodb-0
  
  ports:
    - protocol: TCP
      port: 27017 
      targetPort: 27017
     

