apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: isee-nginx 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: isee-nginx 
  template: 
    metadata: 
      labels: 
        app: isee-nginx 
    spec: 
      containers: 
      - name: isee-nginx 
        image: kamul/nginx-see:latest2
        
        ports: 
        - containerPort: 80
        env: 
        - name: NGINX_PORT
          valueFrom: 
            configMapKeyRef:
              name: backend-config
              key: NGINX_PORT   
        - name: PROXY_BACKEND
          valueFrom: 
            configMapKeyRef:
              name: backend-config
              key: PROXY_BACKEND   
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: isee-nginx-service 
spec: 
  selector: 
    app: isee-nginx 
  type: LoadBalancer 
  ports: 
   
    - protocol: TCP 
      port: 80
      targetPort: 80
      nodePort: 30003