apiVersion: v1 
kind: Service 
metadata:
  name: isee-mongodb
  labels:
    app: isee-mongodb
    app.kubernetes.io/name: isee-mongodb
spec:
  selector:
    app: isee-mongodb
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017 
      targetPort: 27017

