apiVersion: v1
kind: ConfigMap
metadata: 
  name: mongo-config
data:
  mongo-url: mongodb-service
  mongodb.conf: |
    #mongod.conf
    
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
    # network interfaces
    net:
      port: 27017
      bindIp: 127.0.0.1
    
    replication:
      replSetName: rs0
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true

