apiVersion: v1 
kind: Service 
metadata:
  name: mongodb-service
spec:
  type: NodePort
  selector:
    app: isee-mongodb
  ports:
    - name: http
      protocol: TCP
      port: 27017
      nodePort: 30010
     

