apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-backend-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-storage
  resources:
    requests:
      storage: 10Gi