FROM node:lts-hydrogen

WORKDIR /usr/src/app

RUN apt update 
RUN apt install -y ffmpeg
RUN npm i -g npm
RUN npm i -g @nestjs/cli

COPY ./package.json /usr/src/app/package.json

RUN npm i

COPY . /usr/src/app
RUN mkdir -p /usr/src/static


EXPOSE 3000

CMD npm run start

COPY ./default-avatar.jpg /
COPY ./default-thumbnail.jpg /
# Special case, use of .source for the special way hls was implemented
COPY ./default-video.mp4 /default-video.source