FROM node:lts-hydrogen

WORKDIR /usr/src/app

RUN apt update 
RUN apt install -y ffmpeg
RUN npm i -g npm
RUN npm i -g @nestjs/cli

COPY ./package.json /usr/src/app/package.json

RUN npm i

COPY . /usr/src/app
COPY ./src  /usr/src/app/src
RUN mkdir -p /usr/src/static
COPY ./default-avatar.jpg /usr/src/static


EXPOSE ${BACKEND_PORT}

CMD npm run start:dev

COPY ./default-avatar.jpg /
COPY ./default-thumbnail.jpg /
COPY ./default-video.mp4 /