FROM node:lts-hydrogen

WORKDIR /usr/src/app

COPY ./package.json /usr/src/app/package.json

RUN npm i -g npm
RUN npm i -g nodemon
RUN npm i -g @nestjs/cli
RUN npm i

COPY . /usr/src/app

EXPOSE ${BACKEND_PORT}

CMD npm run start:dev